# Generated by Django 3.2 on 2021-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpf',
            name='status',
            field=models.CharField(choices=[('ALLOW', 'DENY')], default='DENY', max_length=5),
        ),
    ]
