# Generated by Django 3.2 on 2021-04-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0002_cpf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpf',
            name='status',
            field=models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], default='DENY', max_length=5),
        ),
    ]
