# Generated by Django 3.2 on 2021-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpf', '0003_alter_cpf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpf',
            name='number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
